// typescript/gql-client-react/src/useOperation.tsx
import { useEffect, useMemo, useState } from 'react';
import type {
    ExecuteResult,
    IExecutor,
    OperationResult,
    OperationVariables,
    RequestContext,
    SyncOperation
} from './types.js';
import hash, { type NotUndefined } from 'object-hash'
import { loadingState } from './loading-state.js';

export interface OperationLoadingState {
    state: 'loading'
}

export interface OperationSuccessState<TResult> extends ExecuteResult<TResult> {
    state: 'success'
}

export interface OperationFailureState {
    state: 'failure'
    error: Error
}

export type OperationState<TResult> =
    OperationLoadingState |
    OperationSuccessState<TResult> |
    OperationFailureState

export function useOperation<
    T extends SyncOperation<unknown, unknown>,
    TRequestContext extends RequestContext
>(
    executor: IExecutor<TRequestContext>,
    operation: T,
    variables: OperationVariables<T>,
    requestContext: TRequestContext
): OperationState<OperationResult<T>> {
    const [state, setState] = useState<OperationState<OperationResult<T>>>(
        loadingState
    )
    const memoizedVariables = useMemo(
        () => variables, [hash(variables as NotUndefined)]
    )
    const memoizedRequestContext = useMemo(
        () => requestContext, [hash(requestContext)]
    )
    useEffect(
        () => {
            executor.executeSync(operation, variables, requestContext)
                .then(result => setState({ state: 'success', ...result }))
                .catch(error => setState({ state: 'failure', error }))
            return () => setState(loadingState)
        },
        [
            setState,
            executor,
            operation,
            memoizedVariables,
            memoizedRequestContext
        ]
    )
    return state
}

// typescript/gql-client-vue/src/useOperation.tsx
import {
    isRef,
    onUnmounted,
    shallowRef,
    ShallowRef,
    watch,
    type Ref,
} from 'vue'
import { loadingState } from './loading-state.js'
import type {
    ExecuteResult,
    IExecutor,
    OperationResult,
    OperationVariables,
    RequestContext,
    SyncOperation,
} from './types.js'

export interface OperationLoadingState {
    state: 'loading'
}

export interface OperationSuccessState<TResult> extends ExecuteResult<TResult> {
    state: 'success'
}

export interface OperationFailureState {
    state: 'failure'
    error: Error
}

export type OperationState<TResult> =
    | OperationLoadingState
    | OperationSuccessState<TResult>
    | OperationFailureState

export function useOperation<
    T extends SyncOperation<unknown, unknown>,
    TRequestContext extends RequestContext,
>(
    executor: IExecutor<TRequestContext>,
    operation: T,
    variables: OperationVariables<T> | Ref<OperationVariables<T>>,
    requestContext: TRequestContext | Ref<TRequestContext>,
): ShallowRef<OperationState<OperationResult<T>>> {
    const state = shallowRef<OperationState<OperationResult<T>>>(loadingState)

    watch(
        [
            () => executor,
            () => operation,
            () => (isRef(variables) ? variables.value : variables),
            () =>
                isRef(requestContext) ? requestContext.value : requestContext,
        ],
        ([exec, op, vars, ctx]) => {
            exec.executeSync(op, vars, ctx)
                .then((result) => {
                    state.value = { state: 'success', ...result }
                })
                .catch((error) => {
                    state.value = { state: 'failure', error: error as Error }
                })
        },
        { immediate: true, deep: true },
    )

    onUnmounted(() => {
        state.value = loadingState
    })

    return state
}
